name: Feature Request
description: Thought of a neat feature for acmcsuf.com?
labels: 'enhancement'
body:
  - type: markdown
    attributes:
      value: |
        ![logo](https://raw.githubusercontent.com/EthanThatOneKid/acmcsuf.com/main/static/assets/svg/about-illustration.svg)
  - type: textarea
    attributes:
      label: What's your idea?
      description: |
        Please elaborate on your idea so that the engineering team can turn it into a reality.
      placeholder: Type away! Feel free to drag-and-drop any screenshots here.
    validations:
      required: false
